### ISSUE TITLE
About full slam integration 

### ISSUE THREAD

**Issue by gisbi-kim** [keenan-burnett/yeti_radar_odometry#1]
I really enjoyed the paper and have been waiting for the code to release.

This is not an issue, but a proposal,
We have a good-working and light-weight place recognition method for the radar,
https://github.com/irapkaist/scancontext/tree/master/fast_evaluator_radar

so in my opinion, an integration with arbitrary keyframe-based radar odometry (e.g., the yeti here)
is easy for the RadarScanContext, to achieve a full SLAM framework.

and obviously, radar-slam in urban environments has vivid benefits than other sensors such as lidar, as you know. 
Thus I'm wondering if your group has a plan to fulfill the place recognition module, which is I actually wanna see that.

I'd say again thank you for the great resource to the community.

**Comment by keenan-burnett** [comment]
Hi Giseop,

Thanks for this suggestion. We may eventually publish a full metric mapping and localization pipeline this year, but our focus will likely not be on SLAM. In any case, a place recognition algorithm may prove useful for metric localization. I'll take a look at your repository when I get a chance.

In terms of our plans for place recognition: I'm not personally planning on working on this, but it's possible that someone else in ASRL might work on it. Currently we don't have anyone planning to work on this but it's possible. Our opinion on the matter is that place recognition / SLAM is less important for self-driving vehicles where a GPS sensor can be used for "place recognition" with the same accuracy. Oftentimes a map is constructed beforehand, making the mapping-then-localization paradigm more popular than SLAM for self-driving vehicles nowadays.

Thanks again for your kind words.

**Comment by gisbi-kim** [comment]
@keenan-burnett thank you!
