### ISSUE TITLE
About load_radar funtion in radar_utils.cpp

### ISSUE THREAD

**Issue by phamquandung** [keenan-burnett/yeti_radar_odometry#2]
Hi Keenan Burnett,

Your research is really interesting. I really enjoy the code you released. Thank you for your great work. 

I try to integrate your work with my current research. However, there is one thing that I do not really understand so I would like to ask you. So, for the load_radar function, I realize that there is a code line as:
`for (int j = 42; j < range_bins; j++) {
            fft_data.at<float>(i, j) = (float)*(byteArray + 11 + j) / 255.0;
        }`

As far as I know, in Oxford dataset, the data from the column 12 to end is fft_data. Why did you start j at 42? In my opinion, j should be 0.

Thank you for your time and consideration.

**Comment by keenan-burnett** [comment]
Hi phamquandung,
You're correct that the actual data starts from zero. However, in my experience, it is useful to mask out the radar data within a certain distance to the sensor (42 * radar resolution). This essentially sets those bins to zero, so I skip processing them. It probably should be a function parameter with a default value set to 42 with better documentation, perhaps you can do that on your own fork 😉
